// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://urswlpolvszzqzwmdxjx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVyc3dscG9sdnN6enF6d21keGp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwODE5MjIsImV4cCI6MjA2NTY1NzkyMn0.DpZzmcE92cddC4ZmJK5SZ1EnPocBnc1XoppS5acZcs8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);